# Base configs
baseurl: "https://ravikalla.github.io/photos"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "World Leaders and Flags"
subtitle: "Identify the leaders!"
author: "Ravi Kalla"
header:
 title: "World Leaders"
 subtitle: "designed by Ravi Kalla"
footer:
 name: "Hey there, my name is Ravi Kalla"
 bio: "I am a dad of 2 kids and Software Architect by profession"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ravikalla/photos\">fork me on github</a> ;)"
bio: "I am a dad of 2 kids and Software Architect by profession"
publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ravikalla/photos\">fork me on github</a> ;)"
web_design: "RK"
social_urls:
  facebook: "https://www.facebook.com/ravi.kalla"
  linkedin: "https://www.linkedin.com/in/ravikalla"
  github: "https://github.com/ravikalla"
